using System;
using System.Collections.Generic;
using JLChnToZ.LuckyPlayer.WeightedRandomizer;

namespace JLChnToZ.LuckyPlayer {
    /// <summary>
    /// Player lucky controller
    /// </summary>
    /// <remarks>You can inherit this class to add customizaton such as changing luckyness algorithm.</remarks>
    public class PlayerLuck {
        protected double luckyness;
        protected Random randomizer;
        /// <summary>
        /// Current player's luckyness
        /// </summary>
        public double Luckyness {
            get { return luckyness; }
        }

        /// <summary>
        /// Constructor with initial 1 luckyness defiend.
        /// </summary>
        public PlayerLuck() {
            luckyness = 1;
        }

        /// <summary>
        /// Constructor with custom luckyness defined.
        /// </summary>
        /// <param name="luck">Initial luckyness</param>
        public PlayerLuck(double luck) {
            luckyness = luck;
        }

        /// <summary>
        /// Gets a random item from the <paramref name="collection"/>, and do further process for luckyness adjustment.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="collection">The collection pool</param>
        /// <param name="random">Optional randomizer</param>
        /// <returns>The item selected</returns>
        public T HandleWithLuck<T>(WeightedCollection<T> collection, Random random = null) {
            if(random == null) {
                if(randomizer == null)
                    randomizer = new Random();
                random = randomizer;
            }
            return HandleWithLuck(collection, random.NextDouble());
        }

        /// <summary>
        /// Gets a random item from the <paramref name="collection"/> from random value given by caller, and do further process for luckyness adjustment.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="collection">The collection pool</param>
        /// <param name="randomValue">The random value generated by caller</param>
        /// <returns>The item selected</returns>
        /// <remarks>This overloaded method is for more advanced uses, which require callers to generate the random number by themself then passing it in.</remarks>
        public T HandleWithLuck<T>(WeightedCollection<T> collection, double randomValue) {
            if(collection == null) throw new ArgumentNullException("collection");
            var weightMapper = collection as IDictionary<T, IItemWeight<T>>;
            LuckyController<T> luckControl;
            foreach(var itemWeight in weightMapper.Values) {
                luckControl = itemWeight as LuckyController<T>;
                if(luckControl == null) continue;
                luckControl.luckInstance = this;
            }
            T result = collection.GetRandomItem(randomValue);
            if((luckControl = weightMapper[result] as LuckyController<T>) != null) {
                LuckyControl(luckControl.rare);
                if(luckyness < double.Epsilon) luckyness = double.Epsilon;
            }
            return result;
        }

        protected virtual void LuckyControl(double resultRarity) {
            if(resultRarity <= 0)
                luckyness += Math.Pow(2, resultRarity);
            else
                luckyness /= Math.Pow(2, resultRarity);
        }
    }
}
